travis:
  secure:
    BINSTAR_TOKEN: EMXBW8ERg1aN3p6j25quE993rYIPVw+O9NlBmp9GFfh/afHPD7cMyBX+o7ONXKHvtGj5+ERd2Ir+Ci0x8KkT6p3PEipRmcT675ovNA3H3GQs8hFSjcbh8aWJbhfvC6zyNM9e34wCUHWsJhv5fn7/fCPgrI7Pmq+spkUwkzQWKmcuImlKAU9bVerRC2t62oblCR0uMC3YjmUtJ0a5xhHnXj+Ijzo5ynkuiaTzFAlCyi9a5yR30oim/jxblbMivTdzoQVwy7yB6yszVPaiVY/LneTt+0e4GcqvGaUIN6oxUz2mbVNu2W8CPAdbMSM39cJ6Yi1mdX8UfX7kJO9tVGh8A3E+MowGbAAHwUplnweVXoFTbLIzyZ1O8d7EBiWHtZmHaUyaTc8YnyXrwBOPcJVKbnI2Lc1CYjPS7mG6NEKjD+g+07qAAmDg61cwCpr8Wd8TEa6OCPuhpK3q8pqwgcghzdjml1lZ+lXIssuHunMFt3da/sbEg0h260eGN1eCq94/2AhhMzYQWSbijQ5kUYkRFm5gK38WGPtGdNUyJJmdxfesj5PNgujHAw40kBPQVtZrd4VXYhswUMODtWnEeAQqofxRHG93oIbtYg2kXBJPjp3tmaj3TkJX+AIDixxZpyYp8x57ISF8M5du3iKMUyW/lWUL7jAFQ+LC/hHoDkCw50Q=
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  pkg_format: '2'
